{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepblue",
    "module": "gradle_plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle_plugin-0.0.1.jar",
          "url": "gradle_plugin-0.0.1.jar",
          "size": 26251,
          "sha512": "9fc536ad3187de94f61fd6e165e8146373159546e4ad4213a0b04fd9bc845fc876825b3f87bdbb6c07676a81c8e50ae6f10fffb66864d3bf28c9257f5a65a6f4",
          "sha256": "986428f1f7264be61eccecdb8eb1c56b4acc5643cfd2d0587f63cc1c33bcd721",
          "sha1": "0796e4fbe556222b4136999e0d77deddd2dd44c6",
          "md5": "0ffae7fda3a037cfef706cbfeac11f95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle_plugin-0.0.1.jar",
          "url": "gradle_plugin-0.0.1.jar",
          "size": 26251,
          "sha512": "9fc536ad3187de94f61fd6e165e8146373159546e4ad4213a0b04fd9bc845fc876825b3f87bdbb6c07676a81c8e50ae6f10fffb66864d3bf28c9257f5a65a6f4",
          "sha256": "986428f1f7264be61eccecdb8eb1c56b4acc5643cfd2d0587f63cc1c33bcd721",
          "sha1": "0796e4fbe556222b4136999e0d77deddd2dd44c6",
          "md5": "0ffae7fda3a037cfef706cbfeac11f95"
        }
      ]
    }
  ]
}
